draw_set_color(c_black)
draw_text( 20, 60, "Player nuts: " + string(obj_player.nuts))
draw_text( 20, 80, "Base nuts: " + string(obj_base.nuts))
draw_text( 20, 100, "movespeed: " + string(obj_player.movespeed))
draw_set_color(c_white)